{
  "openapi": "3.0.0",
  "info": {
    "title": "Brain Agriculture",
    "version": "1.0.0",
    "description": "Bem vindo ao projeto do teste técnico Brain Agriculture! Feito com Adonisjs, combina um backend robusto com uma developer experience sensacional."
  },
  "components": {
    "responses": {
      "Forbidden": {
        "description": "Access token is missing or invalid"
      },
      "Accepted": {
        "description": "The request was accepted"
      },
      "Created": {
        "description": "The resource has been created"
      },
      "NotFound": {
        "description": "The resource has been created"
      },
      "NotAcceptable": {
        "description": "The resource has been created"
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "schemas": {
      "Any": {
        "description": "Any JSON object not defined as schema"
      },
      "Planting": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": false,
            "example": "38f53e85-e966-407e-87fb-4f728b30369d"
          },
          "propertyId": {
            "type": "string",
            "nullable": false,
            "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72"
          },
          "harvest": {
            "type": "string",
            "nullable": false,
            "example": "2020"
          },
          "culture": {
            "type": "string",
            "nullable": false,
            "example": "Arroz"
          },
          "createdAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          },
          "updatedAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          }
        },
        "required": [
          "id",
          "propertyId",
          "harvest",
          "culture",
          "createdAt",
          "updatedAt"
        ],
        "description": "Planting (Interface)"
      },
      "Producer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": false,
            "example": "4a6b030a-e75e-44e9-b046-7c842ef89ec2"
          },
          "name": {
            "type": "string",
            "nullable": false,
            "example": "Lucas Vieira"
          },
          "documentType": {
            "type": "string",
            "nullable": false,
            "example": "CPF"
          },
          "document": {
            "type": "string",
            "nullable": false,
            "example": "19216801099"
          },
          "createdAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          },
          "updatedAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          }
        },
        "required": [
          "id",
          "name",
          "documentType",
          "document",
          "createdAt",
          "updatedAt"
        ],
        "description": "Producer (Interface)"
      },
      "Property": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": false,
            "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72"
          },
          "producerId": {
            "type": "string",
            "nullable": false,
            "example": "4a6b030a-e75e-44e9-b046-7c842ef89ec2"
          },
          "farmName": {
            "type": "string",
            "nullable": false,
            "example": "Mini Fazenda"
          },
          "city": {
            "type": "string",
            "nullable": false,
            "example": "Formosa"
          },
          "state": {
            "type": "string",
            "nullable": false,
            "example": "GO"
          },
          "totalArea": {
            "type": "number",
            "nullable": false,
            "example": 400
          },
          "arableArea": {
            "type": "number",
            "nullable": false,
            "example": 100
          },
          "vegetationArea": {
            "type": "number",
            "nullable": false,
            "example": 200
          },
          "createdAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          },
          "updatedAt": {
            "type": "string",
            "nullable": false,
            "format": "date-time",
            "example": "2021-03-23T16:13:08.489+01:00"
          }
        },
        "required": [
          "id",
          "producerId",
          "farmName",
          "city",
          "state",
          "totalArea",
          "arableArea",
          "vegetationArea",
          "createdAt",
          "updatedAt"
        ],
        "description": "Property (Interface)"
      },
      "PaginationMeta": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "example": 100,
            "nullable": false
          },
          "page": {
            "type": "number",
            "example": 2,
            "nullable": false
          },
          "perPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "currentPage": {
            "type": "number",
            "example": 3,
            "nullable": false
          },
          "lastPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "firstPage": {
            "type": "number",
            "example": 1,
            "nullable": false
          },
          "lastPageUrl": {
            "type": "string",
            "example": "/?page=10",
            "nullable": false
          },
          "firstPageUrl": {
            "type": "string",
            "example": "/?page=1",
            "nullable": false
          },
          "nextPageUrl": {
            "type": "string",
            "example": "/?page=6",
            "nullable": false
          },
          "previousPageUrl": {
            "type": "string",
            "example": "/?page=5",
            "nullable": false
          }
        }
      },
      "PlantingPayload": {
        "type": "object",
        "properties": {
          "harvest": {
            "type": "string",
            "nullable": false,
            "example": "2021"
          },
          "culture": {
            "type": "string",
            "nullable": false,
            "example": "Soja"
          }
        },
        "required": [
          "harvest",
          "culture"
        ],
        "description": "PlantingPayload (Interface)"
      },
      "PlantingUpdatePayload": {
        "type": "object",
        "properties": {
          "harvest": {
            "type": "string",
            "nullable": false,
            "example": "2021"
          },
          "culture": {
            "type": "string",
            "nullable": false,
            "example": "Soja"
          }
        },
        "description": "PlantingUpdatePayload (Interface)"
      },
      "ProducerPayload": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": false,
            "example": "Marco Aurélio"
          },
          "documentType": {
            "type": "string",
            "nullable": false,
            "example": "CPF"
          },
          "document": {
            "type": "string",
            "nullable": false,
            "example": "85430692034"
          }
        },
        "required": [
          "name",
          "documentType",
          "document"
        ],
        "description": "ProducerPayload (Interface)"
      },
      "ProducerUpdatePayload": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": false,
            "example": "Máximus Décimus Meridius"
          },
          "documentType": {
            "type": "string",
            "nullable": false,
            "example": "CPF"
          },
          "document": {
            "type": "string",
            "nullable": false,
            "example": "95145771088"
          }
        },
        "description": "ProducerUpdatePayload (Interface)"
      },
      "PropertyPayload": {
        "type": "object",
        "properties": {
          "farmName": {
            "type": "string",
            "nullable": false,
            "example": "Colheita Feliz"
          },
          "city": {
            "type": "string",
            "nullable": false,
            "example": "Cascavel"
          },
          "state": {
            "type": "string",
            "nullable": false,
            "example": "PR"
          },
          "totalArea": {
            "type": "number",
            "nullable": false,
            "example": 100
          },
          "arableArea": {
            "type": "number",
            "nullable": false,
            "example": 50
          },
          "vegetationArea": {
            "type": "number",
            "nullable": false,
            "example": 50
          }
        },
        "required": [
          "farmName",
          "city",
          "state",
          "totalArea",
          "arableArea",
          "vegetationArea"
        ],
        "description": "PropertyPayload (Interface)"
      },
      "PropertyUpdatePayload": {
        "type": "object",
        "properties": {
          "farmName": {
            "type": "string",
            "nullable": false,
            "example": "Mini Fazenda"
          },
          "city": {
            "type": "string",
            "nullable": false,
            "example": "Cascavel"
          },
          "state": {
            "type": "string",
            "nullable": false,
            "example": "PR"
          },
          "totalArea": {
            "type": "number",
            "nullable": false,
            "example": 500
          },
          "arableArea": {
            "type": "number",
            "nullable": false,
            "example": 250
          },
          "vegetationArea": {
            "type": "number",
            "nullable": false,
            "example": 250
          }
        },
        "description": "PropertyUpdatePayload (Interface)"
      }
    }
  },
  "paths": {
    "/producers": {
      "get": {
        "summary": "Retorna todos os produtores (index)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/producer_controller.ts_ - **index**",
        "operationId": "getProducers",
        "parameters": [],
        "tags": [
          "PRODUCERS"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Producer"
                  }
                },
                "example": [
                  {
                    "id": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
                    "name": "Lucas Vieira",
                    "documentType": "CPF",
                    "document": "19216801099",
                    "createdAt": "2021-03-23T16:13:08.489+01:00",
                    "updatedAt": "2021-03-23T16:13:08.489+01:00"
                  },
                  {
                    "id": "b796b7f0-3b38-4f98-bbdf-f7ecdcac1e07",
                    "name": "João Silva",
                    "documentType": "CPF",
                    "document": "19216801099",
                    "createdAt": "2021-03-23T16:13:08.489+01:00",
                    "updatedAt": "2021-03-23T16:13:08.489+01:00"
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Nenhum produtor encontrado"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "post": {
        "summary": "Cadastrar produtor (store)",
        "description": "Returns **201** (Created) as **text/plain**\n\n _app/controllers/producer_controller.ts_ - **store**",
        "operationId": "createProducer",
        "parameters": [],
        "tags": [
          "PRODUCERS"
        ],
        "responses": {
          "201": {
            "content": {
              "text/plain": {
                "example": "Produtor cadastrado com sucesso"
              }
            },
            "description": "Returns **201** (Created) as **text/plain**"
          },
          "400": {
            "content": {
              "text/plain": {
                "example": "Dados inválidos"
              }
            },
            "description": "Returns **400** (Bad Request) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProducerPayload"
              },
              "example": {
                "name": "Lionel Messi",
                "documentType": "CPF",
                "document": "05188125021"
              }
            }
          }
        }
      }
    },
    "/producers/{id}": {
      "get": {
        "summary": "Retorna um produtor (show)",
        "description": "Retorna um produtor existente no sistema pelo seu ID\n\n _app/controllers/producer_controller.ts_ - **show**",
        "operationId": "getProducerById",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do produtor",
            "schema": {
              "example": "b796b7f0-3b38-4f98-bbdf-f7ecdcac1e07",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PRODUCERS"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Producer"
                },
                "example": {
                  "id": "b796b7f0-3b38-4f98-bbdf-f7ecdcac1e07",
                  "name": "Carlos Andrade",
                  "documentType": "CPF",
                  "document": "19216801099",
                  "createdAt": "2021-03-23T16:13:08.489+01:00",
                  "updatedAt": "2021-03-23T16:13:08.489+01:00"
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Produtor não encontrado"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "put": {
        "summary": "Atualizar produtor (update)",
        "description": "Atualiza um produtor existente do sistema pelo seu ID\n\n _app/controllers/producer_controller.ts_ - **update**",
        "operationId": "updateProducer",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do produtor",
            "schema": {
              "example": "b796b7f0-3b38-4f98-bbdf-f7ecdcac1e07",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PRODUCERS"
        ],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "Produtor atualizado com sucesso"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Produtor não encontrado"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProducerUpdatePayload"
              },
              "example": {
                "name": "Cristiano Ronaldo",
                "documentType": "CPF",
                "document": "54792462088"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar produtor (delete)",
        "description": "Remove um produtor existente do sistema pelo seu ID\n\n _app/controllers/producer_controller.ts_ - **delete**",
        "operationId": "deleteProducer",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do produtor",
            "schema": {
              "example": "b796b7f0-3b38-4f98-bbdf-f7ecdcac1e07",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PRODUCERS"
        ],
        "responses": {
          "204": {
            "content": {
              "text/plain": {
                "example": "Produtor removido com sucesso"
              }
            },
            "description": "Returns **204** (No Content) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Produtor não encontrado"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      }
    },
    "/properties/producer/{id}": {
      "get": {
        "summary": "Retorna fazenda(s) do produtor (indexByProducer)",
        "description": "Retorna uma ou mais fazendas pelo ID de seu proprietário\n\n _app/controllers/property_controller.ts_ - **indexByProducer**",
        "operationId": "getPropertyByProducer",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do produtor",
            "schema": {
              "example": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROPERTIES"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Property"
                  }
                },
                "example": [
                  {
                    "id": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
                    "producerId": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
                    "farmName": "Mini Fazenda",
                    "city": "Formosa",
                    "state": "GO",
                    "totalArea": 500,
                    "arableArea": 250,
                    "vegetationArea": 250,
                    "createdAt": "2021-03-23T16:13:08.489+01:00",
                    "updatedAt": "2021-03-23T16:13:08.489+01:00"
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Nenhuma fazenda encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "post": {
        "summary": "Cadastrar Fazenda (store)",
        "description": "Cadastra uma fazenda no sistema, passando o ID de seu proprietário\n\n _app/controllers/property_controller.ts_ - **store**",
        "operationId": "createProperty",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID do produtor",
            "schema": {
              "example": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROPERTIES"
        ],
        "responses": {
          "201": {
            "content": {
              "text/plain": {
                "example": "Fazenda cadastrada com sucesso"
              }
            },
            "description": "Returns **201** (Created) as **text/plain**"
          },
          "400": {
            "content": {
              "text/plain": {
                "example": "Dados inválidos"
              }
            },
            "description": "Returns **400** (Bad Request) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PropertyPayload"
              },
              "example": {
                "farmName": "Colheita Feliz",
                "city": "Formosa",
                "state": "GO",
                "totalArea": 1000,
                "arableArea": 500,
                "vegetationArea": 500
              }
            }
          }
        }
      }
    },
    "/properties/{id}": {
      "get": {
        "summary": "Retorna uma fazenda (show)",
        "description": "Retorna uma fazenda do sistema pelo seu ID\n\n _app/controllers/property_controller.ts_ - **show**",
        "operationId": "getPropertyById",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da fazenda",
            "schema": {
              "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROPERTIES"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Property"
                },
                "example": {
                  "id": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
                  "producerId": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
                  "farmName": "Mini Fazenda",
                  "city": "Formosa",
                  "state": "GO",
                  "totalArea": 1000,
                  "arableArea": 500,
                  "vegetationArea": 500,
                  "createdAt": "2021-03-23T16:13:08.489+01:00",
                  "updatedAt": "2021-03-23T16:13:08.489+01:00"
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Produtor não encontrado"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "put": {
        "summary": "Atualizar Fazenda (update)",
        "description": "Atualiza uma fazenda existente do sistema pelo seu ID\n\n _app/controllers/property_controller.ts_ - **update**",
        "operationId": "updateProperty",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da fazenda",
            "schema": {
              "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROPERTIES"
        ],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "Fazenda atualizada com sucesso"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Fazenda não encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PropertyUpdatePayload"
              },
              "example": {
                "farmName": "Fazenda Rancho Feliz",
                "city": "Cascavel",
                "state": "PR",
                "totalArea": 300,
                "arableArea": 150,
                "vegetationArea": 150
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar fazenda (delete)",
        "description": "Remove uma fazenda existente do sistema pelo seu ID\n\n _app/controllers/property_controller.ts_ - **delete**",
        "operationId": "deleteProperty",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da fazenda",
            "schema": {
              "example": "4a6b030a-e75e-44e9-b046-7c842ef89ec2",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PROPERTIES"
        ],
        "responses": {
          "204": {
            "content": {
              "text/plain": {
                "example": "Fazenda removida com sucesso"
              }
            },
            "description": "Returns **204** (No Content) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Fazenda não encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      }
    },
    "/plantings/property/{id}": {
      "get": {
        "summary": "Retorna cultura(s) da fazenda (indexByProperty)",
        "description": "Retorna todas as culturas uma fazenda pelo seu ID\n\n _app/controllers/planting_controller.ts_ - **indexByProperty**",
        "operationId": "getPlantingsByProperty",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da fazenda",
            "schema": {
              "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PLANTINGS"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Planting"
                  }
                },
                "example": [
                  {
                    "id": "38f53e85-e966-407e-87fb-4f728b30369d",
                    "propertyId": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
                    "harvest": "2021",
                    "culture": "Milho",
                    "createdAt": "2021-03-23T16:13:08.489+01:00",
                    "updatedAt": "2021-03-23T16:13:08.489+01:00"
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Nenhuma cultura encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "post": {
        "summary": "Cadastrar cultura (store)",
        "description": "Cadastra uma nova cultura, passando o ID de sua fazenda\n\n _app/controllers/planting_controller.ts_ - **store**",
        "operationId": "createPlanting",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da fazenda",
            "schema": {
              "example": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PLANTINGS"
        ],
        "responses": {
          "201": {
            "content": {
              "text/plain": {
                "example": "Cultura cadastrada com sucesso"
              }
            },
            "description": "Returns **201** (Created) as **text/plain**"
          },
          "400": {
            "content": {
              "text/plain": {
                "example": "Dados inválidos"
              }
            },
            "description": "Returns **400** (Bad Request) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PlantingPayload"
              },
              "example": {
                "harvest": "2025",
                "culture": "Ervilha"
              }
            }
          }
        }
      }
    },
    "/plantings/{id}": {
      "get": {
        "summary": "Retorna cultura por ID (show)",
        "description": "Retorna uma cultura do sistema pelo seu ID\n\n _app/controllers/planting_controller.ts_ - **show**",
        "operationId": "getPlantingById",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da cultura",
            "schema": {
              "example": "cc999c89-7d6b-4cc0-9cdb-eebfe4f171e5",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PLANTINGS"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Planting"
                },
                "example": {
                  "id": "cc999c89-7d6b-4cc0-9cdb-eebfe4f171e5",
                  "propertyId": "61d957a0-0865-4bbb-99b5-b3173cfcda72",
                  "harvest": "2021",
                  "culture": "Milho",
                  "createdAt": "2021-03-23T16:13:08.489+01:00",
                  "updatedAt": "2021-03-23T16:13:08.489+01:00"
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Cultura não encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      },
      "put": {
        "summary": "Atualizar cultura (update)",
        "description": "Atualiza uma cultura existente do sistema pelo seu ID\n\n _app/controllers/planting_controller.ts_ - **update**",
        "operationId": "updatePlanting",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da cultura",
            "schema": {
              "example": "61916569-bb84-4af8-88bb-3d49fabbaa49",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PLANTINGS"
        ],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "Cultura atualizada com sucesso"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Cultura não encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PlantingUpdatePayload"
              },
              "example": {
                "harvest": "2025",
                "culture": "Café"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar cultura (delete)",
        "description": "Remove uma cultura existente do sistema pelo seu ID\n\n _app/controllers/planting_controller.ts_ - **delete**",
        "operationId": "deletePlanting",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "ID da cultura",
            "schema": {
              "example": "61916569-bb84-4af8-88bb-3d49fabbaa49",
              "type": "string"
            },
            "required": true
          }
        ],
        "tags": [
          "PLANTINGS"
        ],
        "responses": {
          "204": {
            "content": {
              "text/plain": {
                "example": "Cultura removida com sucesso"
              }
            },
            "description": "Returns **204** (No Content) as **text/plain**"
          },
          "404": {
            "content": {
              "text/plain": {
                "example": "Cultura não encontrada"
              }
            },
            "description": "Returns **404** (Not Found) as **text/plain**"
          }
        },
        "security": []
      }
    },
    "/dashboard/total": {
      "get": {
        "summary": "Métricas de fazendas e hectares (getTotalStats)",
        "description": "Retorna total de fazendas e total de hectares cadastrados\n\n _app/controllers/property_controller.ts_ - **getTotalStats**",
        "operationId": "getTotalStats",
        "parameters": [],
        "tags": [
          "DASHBOARD"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "totalProperties": 10,
                    "totalHectares": 9000
                  }
                },
                "example": {
                  "agriculturalPercentage": 10,
                  "vegetationPercentage": 9000
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/dashboard/land-use": {
      "get": {
        "summary": "Métricas de culturas (getLandUseStats)",
        "description": "Retorna a relação entre áreas cultiváveis e áreas de vegetação\n\n _app/controllers/property_controller.ts_ - **getLandUseStats**",
        "operationId": "getLandUseStats",
        "parameters": [],
        "tags": [
          "DASHBOARD"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "agriculturalPercentage": 10,
                    "vegetationPercentage": 90
                  }
                },
                "example": {
                  "agriculturalPercentage": 10,
                  "vegetationPercentage": 90
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/dashboard/by-state": {
      "get": {
        "summary": "Métricas fazenda por estado (getPropertiesByState)",
        "description": "Retorna quantidade de fazendas por estado\n\n _app/controllers/property_controller.ts_ - **getPropertiesByState**",
        "operationId": "getPropertiesByState",
        "parameters": [],
        "tags": [
          "DASHBOARD"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "GO": 2,
                    "PR": 2
                  }
                },
                "example": {
                  "GO": 2,
                  "PR": 2
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/dashboard/by-crop": {
      "get": {
        "summary": "Métricas culturas (getPropertiesByCrop)",
        "description": "Retorna a quantidade total de cada cultura\n\n _app/controllers/planting_controller.ts_ - **getPropertiesByCrop**",
        "operationId": "getPropertiesByCrop",
        "parameters": [],
        "tags": [
          "DASHBOARD"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Soja": 10,
                    "Milho": 5
                  }
                },
                "example": {
                  "Soja": 10,
                  "Milho": 5
                }
              }
            },
            "description": "Returns **200** (OK)"
          }
        },
        "security": []
      }
    }
  },
  "tags": [
    {
      "name": "PRODUCERS",
      "description": "Gerenciamento de produtores"
    },
    {
      "name": "PROPERTIES",
      "description": "Gerenciamento de fazendas"
    },
    {
      "name": "PLANTINGS",
      "description": "Gerenciamento de plantios"
    },
    {
      "name": "DASHBOARD",
      "description": "Métricas de dashboard"
    }
  ]
}